version: '3'
services:
  db:
    image: kartoza/postgis:9.6-2.4
    container_name: postgis
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - db
